train:
  epochs_num: 10
  dataset_path: C:\Users\artyo\PycharmProjects\rcnn\combined_dataset
  weights_name_outs: weights_combined_10epochs-2

evaluate:
  weights_name_in: weights_combined_10epochs.pth
  dataset_path: eval_data
  detection_threshold: 0.6