train:
  epochs_num: 2
  dataset_path: C:\Users\artyo\PycharmProjects\rcnn\dataset
  weights_name_outs: weights_improved

eval:
  weights_name_in: weights.pth
  dataset_path: C:\Users\artyo\PycharmProjects\rcnn\eval_data
  detection_threshold: 0.9